/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkWithUsImport } from './routes/work-with-us'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ContactImport } from './routes/contact'
import { Route as ChatImport } from './routes/chat'
import { Route as BeProImport } from './routes/be-pro'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as authenticatedOnlyProfileRouteImport } from './routes/(authenticated-only)/profile/route'
import { Route as authenticatedOnlyBarberShopRouteImport } from './routes/(authenticated-only)/barber-shop/route'
import { Route as authenticatedOnlyBarberScheduleRouteImport } from './routes/(authenticated-only)/barber-schedule/route'
import { Route as authenticatedOnlyAdminRouteImport } from './routes/(authenticated-only)/admin/route'
import { Route as authenticatedOnlyBarberShopRegisterImport } from './routes/(authenticated-only)/barber-shop/register'
import { Route as authenticatedOnlyBarberScheduleNewAppointmentImport } from './routes/(authenticated-only)/barber-schedule/new-appointment'
import { Route as authenticatedOnlyAdminSearchUsersImport } from './routes/(authenticated-only)/admin/search-users'
import { Route as authenticatedOnlyAdminResetPasswordImport } from './routes/(authenticated-only)/admin/reset-password'
import { Route as authenticatedOnlyAdminRemoveAllImport } from './routes/(authenticated-only)/admin/remove-all'
import { Route as authenticatedOnlyAdminPopulateAppointmentsImport } from './routes/(authenticated-only)/admin/populate-appointments'
import { Route as authenticatedOnlyAdminPopulateAllImport } from './routes/(authenticated-only)/admin/populate-all'
import { Route as authenticatedOnlyAdminLastUsersImport } from './routes/(authenticated-only)/admin/last-users'
import { Route as authenticatedOnlyAdminDashboardImport } from './routes/(authenticated-only)/admin/dashboard'
import { Route as authenticatedOnlyProfileUserIdRouteImport } from './routes/(authenticated-only)/profile/$userId/route'
import { Route as authenticatedOnlyBarberShopBarberShopIdRouteImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/route'
import { Route as authenticatedOnlyProfileUserIdIndexImport } from './routes/(authenticated-only)/profile/$userId/index'
import { Route as authenticatedOnlyBarberShopBarberShopIdIndexImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/index'
import { Route as authenticatedOnlyBarberScheduleDashboardIndexImport } from './routes/(authenticated-only)/barber-schedule/dashboard/index'
import { Route as authenticatedOnlyProfileUserIdEditImport } from './routes/(authenticated-only)/profile/$userId/edit'
import { Route as authenticatedOnlyBarberShopBarberShopIdServicesImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/services'
import { Route as authenticatedOnlyBarberShopBarberShopIdSchedulesImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/schedules'
import { Route as authenticatedOnlyBarberShopBarberShopIdEditImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/edit'
import { Route as authenticatedOnlyBarberShopBarberShopIdDashboardImport } from './routes/(authenticated-only)/barber-shop/$barberShopId/dashboard'
import { Route as authenticatedOnlyBarberScheduleDashboardAppointmentIdImport } from './routes/(authenticated-only)/barber-schedule/dashboard/$appointmentId'

// Create/Update Routes

const WorkWithUsRoute = WorkWithUsImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const BeProRoute = BeProImport.update({
  id: '/be-pro',
  path: '/be-pro',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedOnlyProfileRouteRoute =
  authenticatedOnlyProfileRouteImport.update({
    id: '/(authenticated-only)/profile',
    path: '/profile',
    getParentRoute: () => rootRoute,
  } as any)

const authenticatedOnlyBarberShopRouteRoute =
  authenticatedOnlyBarberShopRouteImport.update({
    id: '/(authenticated-only)/barber-shop',
    path: '/barber-shop',
    getParentRoute: () => rootRoute,
  } as any)

const authenticatedOnlyBarberScheduleRouteRoute =
  authenticatedOnlyBarberScheduleRouteImport.update({
    id: '/(authenticated-only)/barber-schedule',
    path: '/barber-schedule',
    getParentRoute: () => rootRoute,
  } as any)

const authenticatedOnlyAdminRouteRoute =
  authenticatedOnlyAdminRouteImport.update({
    id: '/(authenticated-only)/admin',
    path: '/admin',
    getParentRoute: () => rootRoute,
  } as any)

const authenticatedOnlyBarberShopRegisterRoute =
  authenticatedOnlyBarberShopRegisterImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => authenticatedOnlyBarberShopRouteRoute,
  } as any)

const authenticatedOnlyBarberScheduleNewAppointmentRoute =
  authenticatedOnlyBarberScheduleNewAppointmentImport.update({
    id: '/new-appointment',
    path: '/new-appointment',
    getParentRoute: () => authenticatedOnlyBarberScheduleRouteRoute,
  } as any)

const authenticatedOnlyAdminSearchUsersRoute =
  authenticatedOnlyAdminSearchUsersImport.update({
    id: '/search-users',
    path: '/search-users',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminResetPasswordRoute =
  authenticatedOnlyAdminResetPasswordImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminRemoveAllRoute =
  authenticatedOnlyAdminRemoveAllImport.update({
    id: '/remove-all',
    path: '/remove-all',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminPopulateAppointmentsRoute =
  authenticatedOnlyAdminPopulateAppointmentsImport.update({
    id: '/populate-appointments',
    path: '/populate-appointments',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminPopulateAllRoute =
  authenticatedOnlyAdminPopulateAllImport.update({
    id: '/populate-all',
    path: '/populate-all',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminLastUsersRoute =
  authenticatedOnlyAdminLastUsersImport.update({
    id: '/last-users',
    path: '/last-users',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyAdminDashboardRoute =
  authenticatedOnlyAdminDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedOnlyAdminRouteRoute,
  } as any)

const authenticatedOnlyProfileUserIdRouteRoute =
  authenticatedOnlyProfileUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => authenticatedOnlyProfileRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdRouteRoute =
  authenticatedOnlyBarberShopBarberShopIdRouteImport.update({
    id: '/$barberShopId',
    path: '/$barberShopId',
    getParentRoute: () => authenticatedOnlyBarberShopRouteRoute,
  } as any)

const authenticatedOnlyProfileUserIdIndexRoute =
  authenticatedOnlyProfileUserIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOnlyProfileUserIdRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdIndexRoute =
  authenticatedOnlyBarberShopBarberShopIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOnlyBarberShopBarberShopIdRouteRoute,
  } as any)

const authenticatedOnlyBarberScheduleDashboardIndexRoute =
  authenticatedOnlyBarberScheduleDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedOnlyBarberScheduleRouteRoute,
  } as any)

const authenticatedOnlyProfileUserIdEditRoute =
  authenticatedOnlyProfileUserIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => authenticatedOnlyProfileUserIdRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdServicesRoute =
  authenticatedOnlyBarberShopBarberShopIdServicesImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => authenticatedOnlyBarberShopBarberShopIdRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdSchedulesRoute =
  authenticatedOnlyBarberShopBarberShopIdSchedulesImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => authenticatedOnlyBarberShopBarberShopIdRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdEditRoute =
  authenticatedOnlyBarberShopBarberShopIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => authenticatedOnlyBarberShopBarberShopIdRouteRoute,
  } as any)

const authenticatedOnlyBarberShopBarberShopIdDashboardRoute =
  authenticatedOnlyBarberShopBarberShopIdDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedOnlyBarberShopBarberShopIdRouteRoute,
  } as any)

const authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute =
  authenticatedOnlyBarberScheduleDashboardAppointmentIdImport.update({
    id: '/dashboard/$appointmentId',
    path: '/dashboard/$appointmentId',
    getParentRoute: () => authenticatedOnlyBarberScheduleRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/be-pro': {
      id: '/be-pro'
      path: '/be-pro'
      fullPath: '/be-pro'
      preLoaderRoute: typeof BeProImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated-only)/admin': {
      id: '/(authenticated-only)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedOnlyAdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated-only)/barber-schedule': {
      id: '/(authenticated-only)/barber-schedule'
      path: '/barber-schedule'
      fullPath: '/barber-schedule'
      preLoaderRoute: typeof authenticatedOnlyBarberScheduleRouteImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated-only)/barber-shop': {
      id: '/(authenticated-only)/barber-shop'
      path: '/barber-shop'
      fullPath: '/barber-shop'
      preLoaderRoute: typeof authenticatedOnlyBarberShopRouteImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated-only)/profile': {
      id: '/(authenticated-only)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedOnlyProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated-only)/barber-shop/$barberShopId': {
      id: '/(authenticated-only)/barber-shop/$barberShopId'
      path: '/$barberShopId'
      fullPath: '/barber-shop/$barberShopId'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
      parentRoute: typeof authenticatedOnlyBarberShopRouteImport
    }
    '/(authenticated-only)/profile/$userId': {
      id: '/(authenticated-only)/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof authenticatedOnlyProfileUserIdRouteImport
      parentRoute: typeof authenticatedOnlyProfileRouteImport
    }
    '/(authenticated-only)/admin/dashboard': {
      id: '/(authenticated-only)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof authenticatedOnlyAdminDashboardImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/last-users': {
      id: '/(authenticated-only)/admin/last-users'
      path: '/last-users'
      fullPath: '/admin/last-users'
      preLoaderRoute: typeof authenticatedOnlyAdminLastUsersImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/populate-all': {
      id: '/(authenticated-only)/admin/populate-all'
      path: '/populate-all'
      fullPath: '/admin/populate-all'
      preLoaderRoute: typeof authenticatedOnlyAdminPopulateAllImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/populate-appointments': {
      id: '/(authenticated-only)/admin/populate-appointments'
      path: '/populate-appointments'
      fullPath: '/admin/populate-appointments'
      preLoaderRoute: typeof authenticatedOnlyAdminPopulateAppointmentsImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/remove-all': {
      id: '/(authenticated-only)/admin/remove-all'
      path: '/remove-all'
      fullPath: '/admin/remove-all'
      preLoaderRoute: typeof authenticatedOnlyAdminRemoveAllImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/reset-password': {
      id: '/(authenticated-only)/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof authenticatedOnlyAdminResetPasswordImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/admin/search-users': {
      id: '/(authenticated-only)/admin/search-users'
      path: '/search-users'
      fullPath: '/admin/search-users'
      preLoaderRoute: typeof authenticatedOnlyAdminSearchUsersImport
      parentRoute: typeof authenticatedOnlyAdminRouteImport
    }
    '/(authenticated-only)/barber-schedule/new-appointment': {
      id: '/(authenticated-only)/barber-schedule/new-appointment'
      path: '/new-appointment'
      fullPath: '/barber-schedule/new-appointment'
      preLoaderRoute: typeof authenticatedOnlyBarberScheduleNewAppointmentImport
      parentRoute: typeof authenticatedOnlyBarberScheduleRouteImport
    }
    '/(authenticated-only)/barber-shop/register': {
      id: '/(authenticated-only)/barber-shop/register'
      path: '/register'
      fullPath: '/barber-shop/register'
      preLoaderRoute: typeof authenticatedOnlyBarberShopRegisterImport
      parentRoute: typeof authenticatedOnlyBarberShopRouteImport
    }
    '/(authenticated-only)/barber-schedule/dashboard/$appointmentId': {
      id: '/(authenticated-only)/barber-schedule/dashboard/$appointmentId'
      path: '/dashboard/$appointmentId'
      fullPath: '/barber-schedule/dashboard/$appointmentId'
      preLoaderRoute: typeof authenticatedOnlyBarberScheduleDashboardAppointmentIdImport
      parentRoute: typeof authenticatedOnlyBarberScheduleRouteImport
    }
    '/(authenticated-only)/barber-shop/$barberShopId/dashboard': {
      id: '/(authenticated-only)/barber-shop/$barberShopId/dashboard'
      path: '/dashboard'
      fullPath: '/barber-shop/$barberShopId/dashboard'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdDashboardImport
      parentRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
    }
    '/(authenticated-only)/barber-shop/$barberShopId/edit': {
      id: '/(authenticated-only)/barber-shop/$barberShopId/edit'
      path: '/edit'
      fullPath: '/barber-shop/$barberShopId/edit'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdEditImport
      parentRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
    }
    '/(authenticated-only)/barber-shop/$barberShopId/schedules': {
      id: '/(authenticated-only)/barber-shop/$barberShopId/schedules'
      path: '/schedules'
      fullPath: '/barber-shop/$barberShopId/schedules'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdSchedulesImport
      parentRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
    }
    '/(authenticated-only)/barber-shop/$barberShopId/services': {
      id: '/(authenticated-only)/barber-shop/$barberShopId/services'
      path: '/services'
      fullPath: '/barber-shop/$barberShopId/services'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdServicesImport
      parentRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
    }
    '/(authenticated-only)/profile/$userId/edit': {
      id: '/(authenticated-only)/profile/$userId/edit'
      path: '/edit'
      fullPath: '/profile/$userId/edit'
      preLoaderRoute: typeof authenticatedOnlyProfileUserIdEditImport
      parentRoute: typeof authenticatedOnlyProfileUserIdRouteImport
    }
    '/(authenticated-only)/barber-schedule/dashboard/': {
      id: '/(authenticated-only)/barber-schedule/dashboard/'
      path: '/dashboard'
      fullPath: '/barber-schedule/dashboard'
      preLoaderRoute: typeof authenticatedOnlyBarberScheduleDashboardIndexImport
      parentRoute: typeof authenticatedOnlyBarberScheduleRouteImport
    }
    '/(authenticated-only)/barber-shop/$barberShopId/': {
      id: '/(authenticated-only)/barber-shop/$barberShopId/'
      path: '/'
      fullPath: '/barber-shop/$barberShopId/'
      preLoaderRoute: typeof authenticatedOnlyBarberShopBarberShopIdIndexImport
      parentRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteImport
    }
    '/(authenticated-only)/profile/$userId/': {
      id: '/(authenticated-only)/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof authenticatedOnlyProfileUserIdIndexImport
      parentRoute: typeof authenticatedOnlyProfileUserIdRouteImport
    }
  }
}

// Create and export the route tree

interface authenticatedOnlyAdminRouteRouteChildren {
  authenticatedOnlyAdminDashboardRoute: typeof authenticatedOnlyAdminDashboardRoute
  authenticatedOnlyAdminLastUsersRoute: typeof authenticatedOnlyAdminLastUsersRoute
  authenticatedOnlyAdminPopulateAllRoute: typeof authenticatedOnlyAdminPopulateAllRoute
  authenticatedOnlyAdminPopulateAppointmentsRoute: typeof authenticatedOnlyAdminPopulateAppointmentsRoute
  authenticatedOnlyAdminRemoveAllRoute: typeof authenticatedOnlyAdminRemoveAllRoute
  authenticatedOnlyAdminResetPasswordRoute: typeof authenticatedOnlyAdminResetPasswordRoute
  authenticatedOnlyAdminSearchUsersRoute: typeof authenticatedOnlyAdminSearchUsersRoute
}

const authenticatedOnlyAdminRouteRouteChildren: authenticatedOnlyAdminRouteRouteChildren =
  {
    authenticatedOnlyAdminDashboardRoute: authenticatedOnlyAdminDashboardRoute,
    authenticatedOnlyAdminLastUsersRoute: authenticatedOnlyAdminLastUsersRoute,
    authenticatedOnlyAdminPopulateAllRoute:
      authenticatedOnlyAdminPopulateAllRoute,
    authenticatedOnlyAdminPopulateAppointmentsRoute:
      authenticatedOnlyAdminPopulateAppointmentsRoute,
    authenticatedOnlyAdminRemoveAllRoute: authenticatedOnlyAdminRemoveAllRoute,
    authenticatedOnlyAdminResetPasswordRoute:
      authenticatedOnlyAdminResetPasswordRoute,
    authenticatedOnlyAdminSearchUsersRoute:
      authenticatedOnlyAdminSearchUsersRoute,
  }

const authenticatedOnlyAdminRouteRouteWithChildren =
  authenticatedOnlyAdminRouteRoute._addFileChildren(
    authenticatedOnlyAdminRouteRouteChildren,
  )

interface authenticatedOnlyBarberScheduleRouteRouteChildren {
  authenticatedOnlyBarberScheduleNewAppointmentRoute: typeof authenticatedOnlyBarberScheduleNewAppointmentRoute
  authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute: typeof authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute
  authenticatedOnlyBarberScheduleDashboardIndexRoute: typeof authenticatedOnlyBarberScheduleDashboardIndexRoute
}

const authenticatedOnlyBarberScheduleRouteRouteChildren: authenticatedOnlyBarberScheduleRouteRouteChildren =
  {
    authenticatedOnlyBarberScheduleNewAppointmentRoute:
      authenticatedOnlyBarberScheduleNewAppointmentRoute,
    authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute:
      authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute,
    authenticatedOnlyBarberScheduleDashboardIndexRoute:
      authenticatedOnlyBarberScheduleDashboardIndexRoute,
  }

const authenticatedOnlyBarberScheduleRouteRouteWithChildren =
  authenticatedOnlyBarberScheduleRouteRoute._addFileChildren(
    authenticatedOnlyBarberScheduleRouteRouteChildren,
  )

interface authenticatedOnlyBarberShopBarberShopIdRouteRouteChildren {
  authenticatedOnlyBarberShopBarberShopIdDashboardRoute: typeof authenticatedOnlyBarberShopBarberShopIdDashboardRoute
  authenticatedOnlyBarberShopBarberShopIdEditRoute: typeof authenticatedOnlyBarberShopBarberShopIdEditRoute
  authenticatedOnlyBarberShopBarberShopIdSchedulesRoute: typeof authenticatedOnlyBarberShopBarberShopIdSchedulesRoute
  authenticatedOnlyBarberShopBarberShopIdServicesRoute: typeof authenticatedOnlyBarberShopBarberShopIdServicesRoute
  authenticatedOnlyBarberShopBarberShopIdIndexRoute: typeof authenticatedOnlyBarberShopBarberShopIdIndexRoute
}

const authenticatedOnlyBarberShopBarberShopIdRouteRouteChildren: authenticatedOnlyBarberShopBarberShopIdRouteRouteChildren =
  {
    authenticatedOnlyBarberShopBarberShopIdDashboardRoute:
      authenticatedOnlyBarberShopBarberShopIdDashboardRoute,
    authenticatedOnlyBarberShopBarberShopIdEditRoute:
      authenticatedOnlyBarberShopBarberShopIdEditRoute,
    authenticatedOnlyBarberShopBarberShopIdSchedulesRoute:
      authenticatedOnlyBarberShopBarberShopIdSchedulesRoute,
    authenticatedOnlyBarberShopBarberShopIdServicesRoute:
      authenticatedOnlyBarberShopBarberShopIdServicesRoute,
    authenticatedOnlyBarberShopBarberShopIdIndexRoute:
      authenticatedOnlyBarberShopBarberShopIdIndexRoute,
  }

const authenticatedOnlyBarberShopBarberShopIdRouteRouteWithChildren =
  authenticatedOnlyBarberShopBarberShopIdRouteRoute._addFileChildren(
    authenticatedOnlyBarberShopBarberShopIdRouteRouteChildren,
  )

interface authenticatedOnlyBarberShopRouteRouteChildren {
  authenticatedOnlyBarberShopBarberShopIdRouteRoute: typeof authenticatedOnlyBarberShopBarberShopIdRouteRouteWithChildren
  authenticatedOnlyBarberShopRegisterRoute: typeof authenticatedOnlyBarberShopRegisterRoute
}

const authenticatedOnlyBarberShopRouteRouteChildren: authenticatedOnlyBarberShopRouteRouteChildren =
  {
    authenticatedOnlyBarberShopBarberShopIdRouteRoute:
      authenticatedOnlyBarberShopBarberShopIdRouteRouteWithChildren,
    authenticatedOnlyBarberShopRegisterRoute:
      authenticatedOnlyBarberShopRegisterRoute,
  }

const authenticatedOnlyBarberShopRouteRouteWithChildren =
  authenticatedOnlyBarberShopRouteRoute._addFileChildren(
    authenticatedOnlyBarberShopRouteRouteChildren,
  )

interface authenticatedOnlyProfileUserIdRouteRouteChildren {
  authenticatedOnlyProfileUserIdEditRoute: typeof authenticatedOnlyProfileUserIdEditRoute
  authenticatedOnlyProfileUserIdIndexRoute: typeof authenticatedOnlyProfileUserIdIndexRoute
}

const authenticatedOnlyProfileUserIdRouteRouteChildren: authenticatedOnlyProfileUserIdRouteRouteChildren =
  {
    authenticatedOnlyProfileUserIdEditRoute:
      authenticatedOnlyProfileUserIdEditRoute,
    authenticatedOnlyProfileUserIdIndexRoute:
      authenticatedOnlyProfileUserIdIndexRoute,
  }

const authenticatedOnlyProfileUserIdRouteRouteWithChildren =
  authenticatedOnlyProfileUserIdRouteRoute._addFileChildren(
    authenticatedOnlyProfileUserIdRouteRouteChildren,
  )

interface authenticatedOnlyProfileRouteRouteChildren {
  authenticatedOnlyProfileUserIdRouteRoute: typeof authenticatedOnlyProfileUserIdRouteRouteWithChildren
}

const authenticatedOnlyProfileRouteRouteChildren: authenticatedOnlyProfileRouteRouteChildren =
  {
    authenticatedOnlyProfileUserIdRouteRoute:
      authenticatedOnlyProfileUserIdRouteRouteWithChildren,
  }

const authenticatedOnlyProfileRouteRouteWithChildren =
  authenticatedOnlyProfileRouteRoute._addFileChildren(
    authenticatedOnlyProfileRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-pro': typeof BeProRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/admin': typeof authenticatedOnlyAdminRouteRouteWithChildren
  '/barber-schedule': typeof authenticatedOnlyBarberScheduleRouteRouteWithChildren
  '/barber-shop': typeof authenticatedOnlyBarberShopRouteRouteWithChildren
  '/profile': typeof authenticatedOnlyProfileRouteRouteWithChildren
  '/barber-shop/$barberShopId': typeof authenticatedOnlyBarberShopBarberShopIdRouteRouteWithChildren
  '/profile/$userId': typeof authenticatedOnlyProfileUserIdRouteRouteWithChildren
  '/admin/dashboard': typeof authenticatedOnlyAdminDashboardRoute
  '/admin/last-users': typeof authenticatedOnlyAdminLastUsersRoute
  '/admin/populate-all': typeof authenticatedOnlyAdminPopulateAllRoute
  '/admin/populate-appointments': typeof authenticatedOnlyAdminPopulateAppointmentsRoute
  '/admin/remove-all': typeof authenticatedOnlyAdminRemoveAllRoute
  '/admin/reset-password': typeof authenticatedOnlyAdminResetPasswordRoute
  '/admin/search-users': typeof authenticatedOnlyAdminSearchUsersRoute
  '/barber-schedule/new-appointment': typeof authenticatedOnlyBarberScheduleNewAppointmentRoute
  '/barber-shop/register': typeof authenticatedOnlyBarberShopRegisterRoute
  '/barber-schedule/dashboard/$appointmentId': typeof authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute
  '/barber-shop/$barberShopId/dashboard': typeof authenticatedOnlyBarberShopBarberShopIdDashboardRoute
  '/barber-shop/$barberShopId/edit': typeof authenticatedOnlyBarberShopBarberShopIdEditRoute
  '/barber-shop/$barberShopId/schedules': typeof authenticatedOnlyBarberShopBarberShopIdSchedulesRoute
  '/barber-shop/$barberShopId/services': typeof authenticatedOnlyBarberShopBarberShopIdServicesRoute
  '/profile/$userId/edit': typeof authenticatedOnlyProfileUserIdEditRoute
  '/barber-schedule/dashboard': typeof authenticatedOnlyBarberScheduleDashboardIndexRoute
  '/barber-shop/$barberShopId/': typeof authenticatedOnlyBarberShopBarberShopIdIndexRoute
  '/profile/$userId/': typeof authenticatedOnlyProfileUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-pro': typeof BeProRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/admin': typeof authenticatedOnlyAdminRouteRouteWithChildren
  '/barber-schedule': typeof authenticatedOnlyBarberScheduleRouteRouteWithChildren
  '/barber-shop': typeof authenticatedOnlyBarberShopRouteRouteWithChildren
  '/profile': typeof authenticatedOnlyProfileRouteRouteWithChildren
  '/admin/dashboard': typeof authenticatedOnlyAdminDashboardRoute
  '/admin/last-users': typeof authenticatedOnlyAdminLastUsersRoute
  '/admin/populate-all': typeof authenticatedOnlyAdminPopulateAllRoute
  '/admin/populate-appointments': typeof authenticatedOnlyAdminPopulateAppointmentsRoute
  '/admin/remove-all': typeof authenticatedOnlyAdminRemoveAllRoute
  '/admin/reset-password': typeof authenticatedOnlyAdminResetPasswordRoute
  '/admin/search-users': typeof authenticatedOnlyAdminSearchUsersRoute
  '/barber-schedule/new-appointment': typeof authenticatedOnlyBarberScheduleNewAppointmentRoute
  '/barber-shop/register': typeof authenticatedOnlyBarberShopRegisterRoute
  '/barber-schedule/dashboard/$appointmentId': typeof authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute
  '/barber-shop/$barberShopId/dashboard': typeof authenticatedOnlyBarberShopBarberShopIdDashboardRoute
  '/barber-shop/$barberShopId/edit': typeof authenticatedOnlyBarberShopBarberShopIdEditRoute
  '/barber-shop/$barberShopId/schedules': typeof authenticatedOnlyBarberShopBarberShopIdSchedulesRoute
  '/barber-shop/$barberShopId/services': typeof authenticatedOnlyBarberShopBarberShopIdServicesRoute
  '/profile/$userId/edit': typeof authenticatedOnlyProfileUserIdEditRoute
  '/barber-schedule/dashboard': typeof authenticatedOnlyBarberScheduleDashboardIndexRoute
  '/barber-shop/$barberShopId': typeof authenticatedOnlyBarberShopBarberShopIdIndexRoute
  '/profile/$userId': typeof authenticatedOnlyProfileUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-pro': typeof BeProRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/(authenticated-only)/admin': typeof authenticatedOnlyAdminRouteRouteWithChildren
  '/(authenticated-only)/barber-schedule': typeof authenticatedOnlyBarberScheduleRouteRouteWithChildren
  '/(authenticated-only)/barber-shop': typeof authenticatedOnlyBarberShopRouteRouteWithChildren
  '/(authenticated-only)/profile': typeof authenticatedOnlyProfileRouteRouteWithChildren
  '/(authenticated-only)/barber-shop/$barberShopId': typeof authenticatedOnlyBarberShopBarberShopIdRouteRouteWithChildren
  '/(authenticated-only)/profile/$userId': typeof authenticatedOnlyProfileUserIdRouteRouteWithChildren
  '/(authenticated-only)/admin/dashboard': typeof authenticatedOnlyAdminDashboardRoute
  '/(authenticated-only)/admin/last-users': typeof authenticatedOnlyAdminLastUsersRoute
  '/(authenticated-only)/admin/populate-all': typeof authenticatedOnlyAdminPopulateAllRoute
  '/(authenticated-only)/admin/populate-appointments': typeof authenticatedOnlyAdminPopulateAppointmentsRoute
  '/(authenticated-only)/admin/remove-all': typeof authenticatedOnlyAdminRemoveAllRoute
  '/(authenticated-only)/admin/reset-password': typeof authenticatedOnlyAdminResetPasswordRoute
  '/(authenticated-only)/admin/search-users': typeof authenticatedOnlyAdminSearchUsersRoute
  '/(authenticated-only)/barber-schedule/new-appointment': typeof authenticatedOnlyBarberScheduleNewAppointmentRoute
  '/(authenticated-only)/barber-shop/register': typeof authenticatedOnlyBarberShopRegisterRoute
  '/(authenticated-only)/barber-schedule/dashboard/$appointmentId': typeof authenticatedOnlyBarberScheduleDashboardAppointmentIdRoute
  '/(authenticated-only)/barber-shop/$barberShopId/dashboard': typeof authenticatedOnlyBarberShopBarberShopIdDashboardRoute
  '/(authenticated-only)/barber-shop/$barberShopId/edit': typeof authenticatedOnlyBarberShopBarberShopIdEditRoute
  '/(authenticated-only)/barber-shop/$barberShopId/schedules': typeof authenticatedOnlyBarberShopBarberShopIdSchedulesRoute
  '/(authenticated-only)/barber-shop/$barberShopId/services': typeof authenticatedOnlyBarberShopBarberShopIdServicesRoute
  '/(authenticated-only)/profile/$userId/edit': typeof authenticatedOnlyProfileUserIdEditRoute
  '/(authenticated-only)/barber-schedule/dashboard/': typeof authenticatedOnlyBarberScheduleDashboardIndexRoute
  '/(authenticated-only)/barber-shop/$barberShopId/': typeof authenticatedOnlyBarberShopBarberShopIdIndexRoute
  '/(authenticated-only)/profile/$userId/': typeof authenticatedOnlyProfileUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/be-pro'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/work-with-us'
    | '/admin'
    | '/barber-schedule'
    | '/barber-shop'
    | '/profile'
    | '/barber-shop/$barberShopId'
    | '/profile/$userId'
    | '/admin/dashboard'
    | '/admin/last-users'
    | '/admin/populate-all'
    | '/admin/populate-appointments'
    | '/admin/remove-all'
    | '/admin/reset-password'
    | '/admin/search-users'
    | '/barber-schedule/new-appointment'
    | '/barber-shop/register'
    | '/barber-schedule/dashboard/$appointmentId'
    | '/barber-shop/$barberShopId/dashboard'
    | '/barber-shop/$barberShopId/edit'
    | '/barber-shop/$barberShopId/schedules'
    | '/barber-shop/$barberShopId/services'
    | '/profile/$userId/edit'
    | '/barber-schedule/dashboard'
    | '/barber-shop/$barberShopId/'
    | '/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/be-pro'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/work-with-us'
    | '/admin'
    | '/barber-schedule'
    | '/barber-shop'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/last-users'
    | '/admin/populate-all'
    | '/admin/populate-appointments'
    | '/admin/remove-all'
    | '/admin/reset-password'
    | '/admin/search-users'
    | '/barber-schedule/new-appointment'
    | '/barber-shop/register'
    | '/barber-schedule/dashboard/$appointmentId'
    | '/barber-shop/$barberShopId/dashboard'
    | '/barber-shop/$barberShopId/edit'
    | '/barber-shop/$barberShopId/schedules'
    | '/barber-shop/$barberShopId/services'
    | '/profile/$userId/edit'
    | '/barber-schedule/dashboard'
    | '/barber-shop/$barberShopId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/be-pro'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/work-with-us'
    | '/(authenticated-only)/admin'
    | '/(authenticated-only)/barber-schedule'
    | '/(authenticated-only)/barber-shop'
    | '/(authenticated-only)/profile'
    | '/(authenticated-only)/barber-shop/$barberShopId'
    | '/(authenticated-only)/profile/$userId'
    | '/(authenticated-only)/admin/dashboard'
    | '/(authenticated-only)/admin/last-users'
    | '/(authenticated-only)/admin/populate-all'
    | '/(authenticated-only)/admin/populate-appointments'
    | '/(authenticated-only)/admin/remove-all'
    | '/(authenticated-only)/admin/reset-password'
    | '/(authenticated-only)/admin/search-users'
    | '/(authenticated-only)/barber-schedule/new-appointment'
    | '/(authenticated-only)/barber-shop/register'
    | '/(authenticated-only)/barber-schedule/dashboard/$appointmentId'
    | '/(authenticated-only)/barber-shop/$barberShopId/dashboard'
    | '/(authenticated-only)/barber-shop/$barberShopId/edit'
    | '/(authenticated-only)/barber-shop/$barberShopId/schedules'
    | '/(authenticated-only)/barber-shop/$barberShopId/services'
    | '/(authenticated-only)/profile/$userId/edit'
    | '/(authenticated-only)/barber-schedule/dashboard/'
    | '/(authenticated-only)/barber-shop/$barberShopId/'
    | '/(authenticated-only)/profile/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeProRoute: typeof BeProRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  authenticatedOnlyAdminRouteRoute: typeof authenticatedOnlyAdminRouteRouteWithChildren
  authenticatedOnlyBarberScheduleRouteRoute: typeof authenticatedOnlyBarberScheduleRouteRouteWithChildren
  authenticatedOnlyBarberShopRouteRoute: typeof authenticatedOnlyBarberShopRouteRouteWithChildren
  authenticatedOnlyProfileRouteRoute: typeof authenticatedOnlyProfileRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeProRoute: BeProRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  authenticatedOnlyAdminRouteRoute:
    authenticatedOnlyAdminRouteRouteWithChildren,
  authenticatedOnlyBarberScheduleRouteRoute:
    authenticatedOnlyBarberScheduleRouteRouteWithChildren,
  authenticatedOnlyBarberShopRouteRoute:
    authenticatedOnlyBarberShopRouteRouteWithChildren,
  authenticatedOnlyProfileRouteRoute:
    authenticatedOnlyProfileRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/be-pro",
        "/chat",
        "/contact",
        "/login",
        "/register",
        "/work-with-us",
        "/(authenticated-only)/admin",
        "/(authenticated-only)/barber-schedule",
        "/(authenticated-only)/barber-shop",
        "/(authenticated-only)/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/be-pro": {
      "filePath": "be-pro.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/work-with-us": {
      "filePath": "work-with-us.tsx"
    },
    "/(authenticated-only)/admin": {
      "filePath": "(authenticated-only)/admin/route.tsx",
      "children": [
        "/(authenticated-only)/admin/dashboard",
        "/(authenticated-only)/admin/last-users",
        "/(authenticated-only)/admin/populate-all",
        "/(authenticated-only)/admin/populate-appointments",
        "/(authenticated-only)/admin/remove-all",
        "/(authenticated-only)/admin/reset-password",
        "/(authenticated-only)/admin/search-users"
      ]
    },
    "/(authenticated-only)/barber-schedule": {
      "filePath": "(authenticated-only)/barber-schedule/route.tsx",
      "children": [
        "/(authenticated-only)/barber-schedule/new-appointment",
        "/(authenticated-only)/barber-schedule/dashboard/$appointmentId",
        "/(authenticated-only)/barber-schedule/dashboard/"
      ]
    },
    "/(authenticated-only)/barber-shop": {
      "filePath": "(authenticated-only)/barber-shop/route.tsx",
      "children": [
        "/(authenticated-only)/barber-shop/$barberShopId",
        "/(authenticated-only)/barber-shop/register"
      ]
    },
    "/(authenticated-only)/profile": {
      "filePath": "(authenticated-only)/profile/route.tsx",
      "children": [
        "/(authenticated-only)/profile/$userId"
      ]
    },
    "/(authenticated-only)/barber-shop/$barberShopId": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/route.tsx",
      "parent": "/(authenticated-only)/barber-shop",
      "children": [
        "/(authenticated-only)/barber-shop/$barberShopId/dashboard",
        "/(authenticated-only)/barber-shop/$barberShopId/edit",
        "/(authenticated-only)/barber-shop/$barberShopId/schedules",
        "/(authenticated-only)/barber-shop/$barberShopId/services",
        "/(authenticated-only)/barber-shop/$barberShopId/"
      ]
    },
    "/(authenticated-only)/profile/$userId": {
      "filePath": "(authenticated-only)/profile/$userId/route.tsx",
      "parent": "/(authenticated-only)/profile",
      "children": [
        "/(authenticated-only)/profile/$userId/edit",
        "/(authenticated-only)/profile/$userId/"
      ]
    },
    "/(authenticated-only)/admin/dashboard": {
      "filePath": "(authenticated-only)/admin/dashboard.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/last-users": {
      "filePath": "(authenticated-only)/admin/last-users.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/populate-all": {
      "filePath": "(authenticated-only)/admin/populate-all.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/populate-appointments": {
      "filePath": "(authenticated-only)/admin/populate-appointments.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/remove-all": {
      "filePath": "(authenticated-only)/admin/remove-all.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/reset-password": {
      "filePath": "(authenticated-only)/admin/reset-password.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/admin/search-users": {
      "filePath": "(authenticated-only)/admin/search-users.tsx",
      "parent": "/(authenticated-only)/admin"
    },
    "/(authenticated-only)/barber-schedule/new-appointment": {
      "filePath": "(authenticated-only)/barber-schedule/new-appointment.tsx",
      "parent": "/(authenticated-only)/barber-schedule"
    },
    "/(authenticated-only)/barber-shop/register": {
      "filePath": "(authenticated-only)/barber-shop/register.tsx",
      "parent": "/(authenticated-only)/barber-shop"
    },
    "/(authenticated-only)/barber-schedule/dashboard/$appointmentId": {
      "filePath": "(authenticated-only)/barber-schedule/dashboard/$appointmentId.tsx",
      "parent": "/(authenticated-only)/barber-schedule"
    },
    "/(authenticated-only)/barber-shop/$barberShopId/dashboard": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/dashboard.tsx",
      "parent": "/(authenticated-only)/barber-shop/$barberShopId"
    },
    "/(authenticated-only)/barber-shop/$barberShopId/edit": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/edit.tsx",
      "parent": "/(authenticated-only)/barber-shop/$barberShopId"
    },
    "/(authenticated-only)/barber-shop/$barberShopId/schedules": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/schedules.tsx",
      "parent": "/(authenticated-only)/barber-shop/$barberShopId"
    },
    "/(authenticated-only)/barber-shop/$barberShopId/services": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/services.tsx",
      "parent": "/(authenticated-only)/barber-shop/$barberShopId"
    },
    "/(authenticated-only)/profile/$userId/edit": {
      "filePath": "(authenticated-only)/profile/$userId/edit.tsx",
      "parent": "/(authenticated-only)/profile/$userId"
    },
    "/(authenticated-only)/barber-schedule/dashboard/": {
      "filePath": "(authenticated-only)/barber-schedule/dashboard/index.tsx",
      "parent": "/(authenticated-only)/barber-schedule"
    },
    "/(authenticated-only)/barber-shop/$barberShopId/": {
      "filePath": "(authenticated-only)/barber-shop/$barberShopId/index.tsx",
      "parent": "/(authenticated-only)/barber-shop/$barberShopId"
    },
    "/(authenticated-only)/profile/$userId/": {
      "filePath": "(authenticated-only)/profile/$userId/index.tsx",
      "parent": "/(authenticated-only)/profile/$userId"
    }
  }
}
ROUTE_MANIFEST_END */
